version: "3.8"

services:
  php-fpm:
    container_name: orbis-php-fpm
    build:
      context: ./php-fpm
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./../:/var/www/

  s-nginx:
    container_name: orbis-nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: orbis-postgres
    build:
      context: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: orbis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
  pgadmin_data:
