version: "3.8"

services:
  php-fpm:
    container_name: orbis-php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/var/www/

  s-nginx:
    container_name: orbis-nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: orbis-postgres
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8084:8080"

volumes:
  db_data:
  pgadmin_data:
