name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: |
          ./docker/php-fpm/Dockerfile
          ./docker/nginx/Dockerfile
          ./postgres/Dockerfile
        tags: |
          ghcr.io/${{ github.repository }}/orbis-php-fpm:latest
          ghcr.io/${{ github.repository }}/orbis-nginx:latest
          ghcr.io/${{ github.repository }}/orbis-postgres:latest

    - name: Deploy to AWS
      env:
        AWS_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        # Install the AWS CLI
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

        # Configure AWS CLI
        aws configure set region $AWS_REGION
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

        # Deploy the Docker Compose application to AWS
        aws ecs compose create --file docker-compose.yml --project-name orbis
        aws ecs compose up --launch-type FARGATE
